/** Mọi spritesheet của game: [khóa, đường dẫn trong assets/, rộng khung, cao khung]. Tải một lần ở BootScene. */
export const ASSETS: [string, string, number, number][] = [
  ['char', 'Characters/Basic Charakter Spritesheet.png', 48, 48],
  ['actions', 'Characters/Basic Charakter Actions.png', 48, 48],
  ['chicken', 'Characters/Free Chicken Sprites.png', 16, 16],
  ['grass', 'Tilesets/Grass.png', 16, 16],
  ['dirt', 'Tilesets/Tilled_Dirt_Wide.png', 16, 16],
  ['water', 'Tilesets/Water.png', 16, 16],
  ['fences', 'Tilesets/Fences.png', 16, 16],
  ['roof', 'Tilesets/Wooden_House_Roof_Tilset.png', 16, 16],
  ['walls', 'Tilesets/Wooden_House_Walls_Tilset.png', 16, 16],
  ['interior', 'Tilesets/Wooden House.png', 16, 16],
  ['doors', 'Tilesets/Doors.png', 16, 16],
  ['furniture', 'Objects/Basic_Furniture.png', 16, 16],
  ['plants', 'Objects/Basic_Plants.png', 16, 16],
  ['biome', 'Objects/Basic_Grass_Biom_things.png', 16, 16],
  ['items', 'Objects/Basic_tools_and_meterials.png', 16, 16],
  ['chest', 'Objects/Chest.png', 48, 48],
  // Vẽ thêm theo phong cách Sprout Lands (tools/)
  ['crops', 'Custom/crops.png', 16, 16],
  ['shop', 'Custom/shop.png', 48, 48],
  ['well', 'Custom/well.png', 32, 32],
  ['season', 'Custom/crops_season.png', 16, 16],
  ['icons', 'Custom/icons.png', 16, 16],
  ['portraits', 'Custom/portraits.png', 24, 24],
  ['chickenhouse', 'Objects/Free_Chicken_House.png', 48, 48],
  ['milkgrass', 'Objects/Simple_Milk_and_grass_item.png', 16, 16],
  ['cow', 'Characters/Free Cow Sprites.png', 32, 32],
  ['nest', 'Characters/Egg_And_Nest.png', 16, 16],
  ['egg', 'Objects/Egg_item.png', 16, 16],
  ['barn', 'Custom/barn.png', 80, 64],
  ['shed', 'Custom/shed.png', 64, 48],
  ['trough', 'Custom/trough.png', 48, 16],
  ['cave', 'Custom/cave.png', 32, 32],
  ['mine', 'Custom/mine.png', 16, 16],
  ['npcs', 'Custom/npcs.png', 48, 48],
  ['greenhouse', 'Custom/greenhouse.png', 64, 48],
  ['pets', 'Custom/player/pets.png', 16, 16],
  ['cart', 'Custom/cart.png', 32, 24],
  ['monsters', 'Custom/monsters.png', 16, 16],
];
